import express, { Request, Response } from "express";
import cors from "cors";
import path from "path";
import helmet from "helmet";
import fileUpload from "express-fileupload";
import {
  API_PORT,
  FRONTEND_URL,
  APPLICATION_NAME,
  AUTH_DOMAIN,
  SENTRY_DSN
} from "./config";
import { doHealthCheck } from "./utils/health-check";
import {  portalRouter, userRouter } from "./routes";

import * as Sentry from "@sentry/node";
import { checkJwt } from "./middleware/authz.middleware";
if (SENTRY_DSN.length > 0) Sentry.init({ dsn: SENTRY_DSN });

const app = express();
app.use(express.json({ limit: "25mb" })); // for parsing application/json
app.use(express.urlencoded({ extended: true, limit: "25mb" })); // for parsing application/x-www-form-urlencoded
app.use(fileUpload({ limits: { fileSize: 25000000 } })); // 25mb
app.use(
  helmet.contentSecurityPolicy({
    directives: {
      "default-src": ["'self'", `${AUTH_DOMAIN}`],
      "base-uri": ["'self'"],
      "block-all-mixed-content": [],
      "font-src": ["'self'", "https:", "data:"],
      "frame-ancestors": ["'self'"],
      "img-src": ["'self'", "data:"],
      "object-src": ["'none'"],
      "script-src": ["'self'", "'unsafe-eval'"],
      "script-src-attr": ["'none'"],
      "style-src": ["'self'", "https:", "'unsafe-inline'"]
    }
  })
);


// very basic CORS setup
app.use(
  cors({
    origin: FRONTEND_URL,
    optionsSuccessStatus: 200,
    credentials: true
  })
);

app.get("/api/healthCheck", (req: Request, res: Response) => {
  // app.get("/api/healthCheck",  (req: Request, res: Response) => {
  doHealthCheck(req, res);
});

app.use("/api/user", checkJwt, userRouter);
app.use("/api/portal", checkJwt, portalRouter);

// serves the static files generated by the front-end
app.use(express.static(path.join(__dirname, "web")));

// if no other routes match, just send the front-end
app.use((req: Request, res: Response) => {
  console.log(`Request to ${req.path} served by sendFile`);
  res.sendFile(path.join(__dirname, "web") + "/index.html");
});

const PORT: number = parseInt(API_PORT as string);

app.listen(PORT, async () => {
  console.log(`${APPLICATION_NAME} API listenting on port ${PORT}`);
});
